service:
  repos:
    git:
      uri: git@github.com:appcrossings/appconfig-client.git#master
      root: src/test/resources
      user: null
      password: null
      context: /appx-a
    http:
      uri: https://github.com/appcrossings/appconfig-client/tree/master/src/test/resources
      user: null
      password: null
      context: /appx-b
      fileName: "default.properties"
      mergeStrategy: "default"
    file:
      root: /var/tmp/configs
      context: /appx-c
    classpath:
      root: /config
      context: /appx-d